"""add username_telegram and pilihan_tinggal fields

Revision ID: 3ef5514ba63e
Revises: 1cd84cac8b97
Create Date: 2025-09-01 16:52:43.796872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ef5514ba63e'
down_revision = '1cd84cac8b97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calgot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username_telegram', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('pilihan_tinggal', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calgot', schema=None) as batch_op:
        batch_op.drop_column('pilihan_tinggal')
        batch_op.drop_column('username_telegram')

    # ### end Alembic commands ###
